schema_version = "1.0.0"
id = "stablegen"
version = "0.3.1"
name = "StableGen"
tagline = "AI-Powered 3D Asset Generation & Texturing"
maintainer = "Ondrej Sakala <sakalaondrej@gmail.com>"
type = "add-on"
blender_version_min = "4.2.0"

website = "https://github.com/sakalond/StableGen"

tags = ["Material", "Paint", "UV", "Mesh", "Import-Export"]

license = ["SPDX:GPL-3.0-or-later"]

platforms = ["windows-x64", "linux-x64", "macos-arm64"]

wheels = [
  "./wheels/websocket_client-1.8.0-py3-none-any.whl",
  "./wheels/websockets-15.0.1-py3-none-any.whl",
  "./wheels/imageio-2.37.0-py3-none-any.whl",
  "./wheels/trimesh-4.12.2-py3-none-any.whl",

  # Windows specific

  "./wheels/imageio_ffmpeg-0.6.0-py3-none-win_amd64.whl",
  "./wheels/opencv_python_headless-4.11.0.86-cp37-abi3-win_amd64.whl",
  "./wheels/pillow-11.2.1-cp311-cp311-win_amd64.whl",
  "./wheels/pillow-11.2.1-cp313-cp313-win_amd64.whl",
  "./wheels/fast_simplification-0.1.13-cp311-abi3-win_amd64.whl",

  # Linux specific

  "./wheels/imageio_ffmpeg-0.6.0-py3-none-manylinux2014_x86_64.whl",
  "./wheels/opencv_python_headless-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/pillow-11.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/pillow-11.2.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/fast_simplification-0.1.12-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",

  # macOS Apple Silicon

  "./wheels/imageio_ffmpeg-0.6.0-py3-none-macosx_11_0_arm64.whl",
  "./wheels/opencv_python_headless-4.11.0.86-cp37-abi3-macosx_13_0_arm64.whl",
  "./wheels/pillow-11.2.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pillow-11.2.1-cp313-cp313-macosx_11_0_arm64.whl",
  "./wheels/fast_simplification-0.1.13-cp311-abi3-macosx_11_0_arm64.whl"
]

[permissions]
network = "Connects to a local ComfyUI server for AI generation"
files = "Saves generated textures, 3D meshes, PBR maps, and exported GIFs"
