const fs = require('fs');
const esbuild = require('esbuild');

// Read the generated ultra Hoi An SVG content
const ultraHoiAnCode = fs.readFileSync('scripts/build_ultra_hoian.cjs', 'utf8');

// Extract the SVG content generated by buildUltraRealisticHoiAnSvg
// We can just require the function and call it!
const path = 'components/login/MidAutumnSvgBackdrop.tsx';
let backdropContent = fs.readFileSync(path, 'utf8');

// Let's get the SVG inner code from test_ultra_hoian.svg
const ultraSvg = fs.readFileSync('scratch/test_ultra_hoian.svg', 'utf8');

// Extract <defs> children
const defsStart = ultraSvg.indexOf('<defs>') + 6;
const defsEnd = ultraSvg.indexOf('</defs>');
const newDefs = ultraSvg.substring(defsStart, defsEnd);

// Extract the artwork elements (everything after </defs> up to </svg>)
const artStart = defsEnd + 7;
const artEnd = ultraSvg.lastIndexOf('</svg>');
let artworkContent = ultraSvg.substring(artStart, artEnd);

// Convert JSX incompatibilities if any:
// stroke-width -> strokeWidth
// stroke-linecap -> strokeLinecap
// stroke-linejoin -> strokeLinejoin
// stroke-dasharray -> strokeDasharray
// stop-color -> stopColor
// stop-opacity -> stopOpacity
// flood-color -> floodColor
// flood-opacity -> floodOpacity
// font-size -> fontSize
// font-weight -> fontWeight
// text-anchor -> textAnchor
// font-family -> fontFamily
// pointer-events -> pointerEvents

function toJsx(str) {
    return str
        .replace(/stroke-width=/g, 'strokeWidth=')
        .replace(/stroke-linecap=/g, 'strokeLinecap=')
        .replace(/stroke-linejoin=/g, 'strokeLinejoin=')
        .replace(/stroke-dasharray=/g, 'strokeDasharray=')
        .replace(/stop-color=/g, 'stopColor=')
        .replace(/stop-opacity=/g, 'stopOpacity=')
        .replace(/flood-color=/g, 'floodColor=')
        .replace(/flood-opacity=/g, 'floodOpacity=')
        .replace(/font-size=/g, 'fontSize=')
        .replace(/font-weight=/g, 'fontWeight=')
        .replace(/text-anchor=/g, 'textAnchor=')
        .replace(/font-family=/g, 'fontFamily=')
        .replace(/pointer-events=/g, 'pointerEvents=')
        .replace(/<!--[\s\S]*?-->/g, ''); // strip HTML comments to avoid Babel JSX parse errors
}

const jsxDefs = toJsx(newDefs);
const jsxArtwork = toJsx(artworkContent);

// Add animations to style in MidAutumnSvgBackdrop
const hoianAnimations = `
                /* HỘI AN ANCIENT TOWN ANIMATIONS */
                @keyframes hoian-boat-bob-1 {
                    0%, 100% { transform: translate(0, 0) rotate(0.8deg); }
                    50% { transform: translate(0, -5px) rotate(-1deg); }
                }
                .animate-hoian-boat-1 {
                    animation: hoian-boat-bob-1 6.5s ease-in-out infinite;
                }

                @keyframes hoian-boat-bob-2 {
                    0%, 100% { transform: translate(0, 0) rotate(-1deg); }
                    50% { transform: translate(0, -6px) rotate(0.8deg); }
                }
                .animate-hoian-boat-2 {
                    animation: hoian-boat-bob-2 7.2s ease-in-out infinite 1.2s;
                }

                @keyframes hoian-hoa-dang-float-1 {
                    0% { transform: translate(0, 0); }
                    50% { transform: translate(14px, -3px); }
                    100% { transform: translate(28px, 1px); }
                }
                @keyframes hoian-hoa-dang-float-2 {
                    0% { transform: translate(0, 0); }
                    50% { transform: translate(-12px, -4px); }
                    100% { transform: translate(-25px, 0px); }
                }
                .animate-hoa-dang-1 {
                    animation: hoian-hoa-dang-float-1 12s ease-in-out infinite alternate;
                }
                .animate-hoa-dang-2 {
                    animation: hoian-hoa-dang-float-2 15s ease-in-out infinite alternate 1.5s;
                }
                .animate-hoa-dang-3 {
                    animation: hoian-hoa-dang-float-1 10s ease-in-out infinite alternate 3s;
                }

                @keyframes hoian-water-shimmer {
                    0%, 100% { opacity: 0.45; }
                    50% { opacity: 0.75; }
                }
                .animate-water-shimmer {
                    animation: hoian-water-shimmer 4.5s ease-in-out infinite;
                }
`;

// Replace the old Hội An section in backdropContent
// Let's find where hoian-ancient-town-artwork is
const oldArtRegex = /\{\/\* =+ \*\/\}\s*\{\/\* 1\.5\. BỨC TRANH SVG ĐỘNG: PHỐ CỔ HỘI AN[\s\S]*?<\/g>\s*(?=\{\/\* 2\. ÁNH MÂY BỤI TINH VÂN)/;

// Wrap boats in animation groups
let wrappedArtwork = jsxArtwork;

// Thuyền 1
wrappedArtwork = wrappedArtwork.replace(/(<!-- SAMPAN BOAT at \(235, 620\) -->[\s\S]*?<\/g>)/, `
<g className="animate-hoian-boat-1" style={{ transformOrigin: '280px 630px' }}>
    $1
</g>
`);

// Thuyền 2
wrappedArtwork = wrappedArtwork.replace(/(<!-- SAMPAN BOAT at \(1550, 650\) -->[\s\S]*?<\/g>)/, `
<g className="animate-hoian-boat-2" style={{ transformOrigin: '1600px 660px' }}>
    $1
</g>
`);

// Thuyền 4
wrappedArtwork = wrappedArtwork.replace(/(<!-- SAMPAN BOAT at \(110, 765\) -->[\s\S]*?<\/g>)/, `
<g className="animate-hoian-boat-1" style={{ transformOrigin: '160px 780px' }}>
    $1
</g>
`);

// Thuyền 5
wrappedArtwork = wrappedArtwork.replace(/(<!-- SAMPAN BOAT at \(1660, 825\) -->[\s\S]*?<\/g>)/, `
<g className="animate-hoian-boat-2" style={{ transformOrigin: '1710px 840px' }}>
    $1
</g>
`);

// Wrap floating lanterns in float animations
wrappedArtwork = wrappedArtwork.replace(/(<g transform="translate\(515, 635\)[\s\S]*?<\/g>\s*<g transform="translate\(385, 705\)[\s\S]*?<\/g>)/, `
<g className="animate-hoa-dang-1">
    $1
</g>
`);

wrappedArtwork = wrappedArtwork.replace(/(<g transform="translate\(595, 755\)[\s\S]*?<\/g>\s*<g transform="translate\(1375, 665\)[\s\S]*?<\/g>)/, `
<g className="animate-hoa-dang-2">
    $1
</g>
`);

wrappedArtwork = wrappedArtwork.replace(/(<g transform="translate\(1475, 765\)[\s\S]*?<\/g>\s*<g transform="translate\(1715, 715\)[\s\S]*?<\/g>)/, `
<g className="animate-hoa-dang-3">
    $1
</g>
`);

// Wrap waves in shimmer animation
wrappedArtwork = wrappedArtwork.replace(/(<g filter="url\(#bloomSoft\)">\s*<path d="M 0,575)/, `
<g filter="url(#bloomSoft)" className="animate-water-shimmer">
    <path d="M 0,575`);

const newTownSection = `
                {/* ============================================================================== */}
                {/* 1.5. BỨC TRANH SVG ĐỘNG: PHỐ CỔ HỘI AN ĐÊM RẰM CHÂN THẬT CAO CẤP */}
                {/* ============================================================================== */}
                <g id="hoian-masterpiece-artwork">
                    ${wrappedArtwork.trim()}
                </g>
`;

if (oldArtRegex.test(backdropContent)) {
    backdropContent = backdropContent.replace(oldArtRegex, newTownSection);
    console.log('Replaced old Hội An artwork with master realistic artwork!');
} else {
    console.log('Regex did not match, looking for insertion point');
    const insertPoint = '{/* 2. ÁNH MÂY BỤI TINH VÂN KHỔNG LỒ */}';
    backdropContent = backdropContent.replace(insertPoint, `${newTownSection}\n${insertPoint}`);
}

// Ensure defs are present
const defsRegex = /\{\/\* HỘI AN ANCIENT TOWN DEFS \*\/\}[\s\S]*?(?=<\/defs>)/;
if (defsRegex.test(backdropContent)) {
    backdropContent = backdropContent.replace(defsRegex, `{/* HỘI AN ANCIENT TOWN MASTER DEFS */}\n${jsxDefs}\n`);
    console.log('Updated Hội An defs!');
}

// Clean up any remaining HTML comments in TSX
backdropContent = backdropContent.replace(/<!--[\s\S]*?-->/g, '');

// Test with esbuild
try {
    esbuild.transformSync(backdropContent, { loader: 'tsx' });
    console.log('esbuild check PASSED for master realistic Hội An backdrop!');
    fs.writeFileSync(path, backdropContent, 'utf8');
    console.log('Successfully written', path);
} catch (err) {
    console.error('esbuild check FAILED:', err.message);
    process.exit(1);
}
