-- Create tvbh_emails table if not exists and grant full permissions
CREATE TABLE IF NOT EXISTS public.tvbh_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_tvbh TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tvbh_emails_ten ON public.tvbh_emails (lower(ten_tvbh));
CREATE INDEX IF NOT EXISTS idx_tvbh_emails_email ON public.tvbh_emails (lower(email));

-- Disable RLS or grant permissions to all roles
ALTER TABLE public.tvbh_emails DISABLE ROW LEVEL SECURITY;
GRANT ALL ON public.tvbh_emails TO postgres, service_role, authenticated, anon;

-- Populate from existing users
INSERT INTO public.tvbh_emails (ten_tvbh, email, updated_at)
SELECT full_name, email, now()
FROM public.users
WHERE email IS NOT NULL AND email != '' AND full_name IS NOT NULL
ON CONFLICT (email) DO UPDATE SET ten_tvbh = EXCLUDED.ten_tvbh, updated_at = now();
